/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE examBaseService PLEASE EDIT ../exam.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exam } from '../../domain/school-ms_db/exam';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Exam.service.ts
 */

/*
 * SCHEMA DB Exam
 *
	{
		averageresult: {
			type: 'Decimal'
		},
		class: {
			type: 'Number',
			required : true
		},
		date: {
			type: 'Date',
			required : true
		},
		done: {
			type: 'Boolean'
		},
		examname: {
			type: 'String',
			required : true
		},
		maxmarks: {
			type: 'Number'
		},
		roomno: {
			type: 'String',
			required : true
		},
		session: {
			type: 'Date',
			required : true
		},
		subjectname: {
			type: 'String',
			required : true
		},
		teachername: {
			type: 'String',
			required : true
		},
		timing: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Class: [{
			type: Schema.ObjectId,
			ref : "Exam"
		}],
		_Exam: [{
			type: Schema.ObjectId,
			ref : "Teacher"
		}],
		_Exam: [{
			type: Schema.ObjectId,
			ref : "Student"
		}],
		_Subject: [{
			type: Schema.ObjectId,
			ref : "Exam"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Exam"
		}],
	}
 *
 */
@Injectable()
export class ExamBaseService {

    contextUrl: string = environment.endpoint + '/exam';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ExamService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Exam): Observable<Exam> {
        return this.http
            .post<Exam>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ExamService.delete
    *   @description CRUD ACTION delete
    *   @param String examname
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ExamService.findBy_Class
    *   @description CRUD ACTION findBy_Class
    *
    */
    findBy_Class(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_Class/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBy_Subject
    *   @description CRUD ACTION findBy_Subject
    *
    */
    findBy_Subject(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_Subject/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBy_Teacher
    *   @description CRUD ACTION findBy_Teacher
    *
    */
    findBy_Teacher(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_Teacher/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findByclass
    *   @description CRUD ACTION findByclass
    *
    */
    findByClass(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findByclass/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBydate
    *   @description CRUD ACTION findBydate
    *
    */
    findByDate(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBydate/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findByexamname
    *   @description CRUD ACTION findByexamname
    *
    */
    findByExamname(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findByexamname/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBysession
    *   @description CRUD ACTION findBysession
    *
    */
    findBySession(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBysession/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBysubjectname
    *   @description CRUD ACTION findBysubjectname
    *
    */
    findBySubjectname(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBysubjectname/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findByteachername
    *   @description CRUD ACTION findByteachername
    *
    */
    findByTeachername(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findByteachername/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.get
    *   @description CRUD ACTION get
    *   @param String examname
    *   @param String id Id resource
    *
    */
    get(id: string): Observable<Exam> {
        return this.http
            .get<Exam>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ExamService.get_Class
    *   @description CRUD ACTION get_Class
    *   @param Number class
    *
    */
    get_Class(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Class')
            .pipe(
                map(response => response)
            );
     }

    /**
    * ExamService.get_Subject
    *   @description CRUD ACTION get_Subject
    *   @param String subjectname
    *
    */
    get_Subject(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Subject')
            .pipe(
                map(response => response)
            );
     }

    /**
    * ExamService.get_Teacher
    *   @description CRUD ACTION get_Teacher
    *   @param String teachername
    *
    */
    get_Teacher(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Teacher')
            .pipe(
                map(response => response)
            );
     }

    /**
    * ExamService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ExamService.update
    *   @description CRUD ACTION update
    *   @param String examname
    *   @param String id Id
    *
    */
    update(item: Exam): Observable<Exam> {
        return this.http
            .post<Exam>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
