/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE lessonBaseService PLEASE EDIT ../lesson.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Lesson } from '../../domain/school-ms_db/lesson';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Lesson.service.ts
 */

/*
 * SCHEMA DB Lesson
 *
	{
		assignment: {
			type: 'Boolean'
		},
		class: {
			type: 'Number',
			required : true
		},
		done: {
			type: 'Boolean'
		},
		lessonname: {
			type: 'String'
		},
		lessonno: {
			type: 'Number',
			required : true
		},
		subjectname: {
			type: 'String',
			required : true
		},
		teachername: {
			type: 'String',
			required : true
		},
		test: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Lesson: [{
			type: Schema.ObjectId,
			ref : "Test"
		}],
		_Subject: [{
			type: Schema.ObjectId,
			ref : "Lesson"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Lesson"
		}],
	}
 *
 */
@Injectable()
export class LessonBaseService {

    contextUrl: string = environment.endpoint + '/lesson';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * LessonService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Lesson): Observable<Lesson> {
        return this.http
            .post<Lesson>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * LessonService.delete
    *   @description CRUD ACTION delete
    *   @param String id id
    *   @param String lessonname
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * LessonService.findBy_Subject
    *   @description CRUD ACTION findBy_Subject
    *
    */
    findBy_Subject(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBy_Subject/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findBy_Teacher
    *   @description CRUD ACTION findBy_Teacher
    *
    */
    findBy_Teacher(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBy_Teacher/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findByassignment
    *   @description CRUD ACTION findByassignment
    *
    */
    findByAssignment(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findByassignment/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findByclass
    *   @description CRUD ACTION findByclass
    *
    */
    findByClass(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findByclass/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findBydone
    *   @description CRUD ACTION findBydone
    *
    */
    findByDone(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBydone/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findBylessonname
    *   @description CRUD ACTION findBylessonname
    *
    */
    findByLessonname(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBylessonname/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findBylessonno
    *   @description CRUD ACTION findBylessonno
    *
    */
    findByLessonno(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBylessonno/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findBysubjectname
    *   @description CRUD ACTION findBysubjectname
    *
    */
    findBySubjectname(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBysubjectname/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findByteachername
    *   @description CRUD ACTION findByteachername
    *
    */
    findByTeachername(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findByteachername/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.findBytest
    *   @description CRUD ACTION findBytest
    *
    */
    findByTest(id: string): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl + '/findBytest/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * LessonService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *   @param String lessonname
    *
    */
    get(id: string): Observable<Lesson> {
        return this.http
            .get<Lesson>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * LessonService.get_Subject
    *   @description CRUD ACTION get_Subject
    *
    */
    get_Subject(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Subject')
            .pipe(
                map(response => response)
            );
     }

    /**
    * LessonService.get_Subject
    *   @description CRUD ACTION get_Subject
    *   @param String subjectname
    *
    */
    get_Subject(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Subject')
            .pipe(
                map(response => response)
            );
     }

    /**
    * LessonService.get_Teacher
    *   @description CRUD ACTION get_Teacher
    *   @param String teachername
    *
    */
    get_Teacher(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Teacher')
            .pipe(
                map(response => response)
            );
     }

    /**
    * LessonService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Lesson[]> {
        return this.http
            .get<Lesson[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * LessonService.update
    *   @description CRUD ACTION update
    *   @param String id id
    *   @param String lessonname
    *
    */
    update(item: Lesson): Observable<Lesson> {
        return this.http
            .post<Lesson>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
