/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE studentBaseService PLEASE EDIT ../student.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Student } from '../../domain/school-ms_db/student';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Student.service.ts
 */

/*
 * SCHEMA DB Student
 *
	{
		class: {
			type: 'Number',
			required : true
		},
		dob: {
			type: 'Date'
		},
		fathersname: {
			type: 'String'
		},
		mothersname: {
			type: 'String'
		},
		percentinlastexam: {
			type: 'Decimal'
		},
		rollno: {
			type: 'String',
			required : true
		},
		studentname: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Class: [{
			type: Schema.ObjectId,
			ref : "Student"
		}],
		_Exam: [{
			type: Schema.ObjectId,
			ref : "Student"
		}],
	}
 *
 */
@Injectable()
export class StudentBaseService {

    contextUrl: string = environment.endpoint + '/student';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * StudentService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Student): Observable<Student> {
        return this.http
            .post<Student>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * StudentService.delete
    *   @description CRUD ACTION delete
    *   @param String id id
    *   @param String studentname
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * StudentService.findBy_Class
    *   @description CRUD ACTION findBy_Class
    *
    */
    findBy_Class(id: string): Observable<Student[]> {
        return this.http
            .get<Student[]>(this.contextUrl + '/findBy_Class/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * StudentService.findByclass
    *   @description CRUD ACTION findByclass
    *
    */
    findByClass(id: string): Observable<Student[]> {
        return this.http
            .get<Student[]>(this.contextUrl + '/findByclass/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * StudentService.findByrollno
    *   @description CRUD ACTION findByrollno
    *
    */
    findByRollno(id: string): Observable<Student[]> {
        return this.http
            .get<Student[]>(this.contextUrl + '/findByrollno/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * StudentService.findBystudentname
    *   @description CRUD ACTION findBystudentname
    *
    */
    findByStudentname(id: string): Observable<Student[]> {
        return this.http
            .get<Student[]>(this.contextUrl + '/findBystudentname/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * StudentService.get
    *   @description CRUD ACTION get
    *   @param String id id
    *   @param String studentname
    *
    */
    get(id: string): Observable<Student> {
        return this.http
            .get<Student>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * StudentService.get_Class
    *   @description CRUD ACTION get_Class
    *   @param Number class
    *
    */
    get_Class(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Class')
            .pipe(
                map(response => response)
            );
     }

    /**
    * StudentService.get_Exam
    *   @description CRUD ACTION get_Exam
    *   @param String examname
    *
    */
    get_Exam(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Exam')
            .pipe(
                map(response => response)
            );
     }

    /**
    * StudentService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Student[]> {
        return this.http
            .get<Student[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * StudentService.update
    *   @description CRUD ACTION update
    *   @param String id id
    *   @param String studentname
    *
    */
    update(item: Student): Observable<Student> {
        return this.http
            .post<Student>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
