/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE subjectBaseService PLEASE EDIT ../subject.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Subject } from '../../domain/school-ms_db/subject';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Subject.service.ts
 */

/*
 * SCHEMA DB Subject
 *
	{
		averageresultinlastexam: {
			type: 'Decimal'
		},
		class: {
			type: 'Number',
			required : true
		},
		period: {
			type: 'Number'
		},
		subjectname: {
			type: 'String',
			required : true
		},
		teachername: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Class: [{
			type: Schema.ObjectId,
			ref : "Subject"
		}],
		_Subject: [{
			type: Schema.ObjectId,
			ref : "Lesson"
		}],
		_Subject: [{
			type: Schema.ObjectId,
			ref : "Exam"
		}],
		_Subject: [{
			type: Schema.ObjectId,
			ref : "Test"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Subject"
		}],
	}
 *
 */
@Injectable()
export class SubjectBaseService {

    contextUrl: string = environment.endpoint + '/subject';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * SubjectService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Subject): Observable<Subject> {
        return this.http
            .post<Subject>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * SubjectService.delete
    *   @description CRUD ACTION delete
    *   @param String id id
    *   @param String subjectname
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SubjectService.findBy_Class
    *   @description CRUD ACTION findBy_Class
    *
    */
    findBy_Class(id: string): Observable<Subject[]> {
        return this.http
            .get<Subject[]>(this.contextUrl + '/findBy_Class/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * SubjectService.findBy_Teacher
    *   @description CRUD ACTION findBy_Teacher
    *
    */
    findBy_Teacher(id: string): Observable<Subject[]> {
        return this.http
            .get<Subject[]>(this.contextUrl + '/findBy_Teacher/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * SubjectService.findByclass
    *   @description CRUD ACTION findByclass
    *
    */
    findByClass(id: string): Observable<Subject[]> {
        return this.http
            .get<Subject[]>(this.contextUrl + '/findByclass/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * SubjectService.findBysubjectname
    *   @description CRUD ACTION findBysubjectname
    *
    */
    findBySubjectname(id: string): Observable<Subject[]> {
        return this.http
            .get<Subject[]>(this.contextUrl + '/findBysubjectname/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * SubjectService.findByteachername
    *   @description CRUD ACTION findByteachername
    *
    */
    findByTeachername(id: string): Observable<Subject[]> {
        return this.http
            .get<Subject[]>(this.contextUrl + '/findByteachername/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * SubjectService.get
    *   @description CRUD ACTION get
    *   @param String id id
    *   @param String subjectname
    *
    */
    get(id: string): Observable<Subject> {
        return this.http
            .get<Subject>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SubjectService.get_Class
    *   @description CRUD ACTION get_Class
    *   @param Number class
    *
    */
    get_Class(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Class')
            .pipe(
                map(response => response)
            );
     }

    /**
    * SubjectService.get_Teacher
    *   @description CRUD ACTION get_Teacher
    *   @param String teachername
    *
    */
    get_Teacher(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Teacher')
            .pipe(
                map(response => response)
            );
     }

    /**
    * SubjectService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Subject[]> {
        return this.http
            .get<Subject[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * SubjectService.update
    *   @description CRUD ACTION update
    *   @param String id id
    *   @param String subjectname
    *
    */
    update(item: Subject): Observable<Subject> {
        return this.http
            .post<Subject>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
