/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE teacherBaseService PLEASE EDIT ../teacher.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Teacher } from '../../domain/school-ms_db/teacher';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Teacher.service.ts
 */

/*
 * SCHEMA DB Teacher
 *
	{
		class: {
			type: 'Number',
			required : true
		},
		teachername: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Class: [{
			type: Schema.ObjectId,
			ref : "Teacher"
		}],
		_Exam: [{
			type: Schema.ObjectId,
			ref : "Teacher"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Class"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Subject"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Lesson"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Exam"
		}],
		_Teacher: [{
			type: Schema.ObjectId,
			ref : "Test"
		}],
	}
 *
 */
@Injectable()
export class TeacherBaseService {

    contextUrl: string = environment.endpoint + '/teacher';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * TeacherService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Teacher): Observable<Teacher> {
        return this.http
            .post<Teacher>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * TeacherService.delete
    *   @description CRUD ACTION delete
    *   @param String id id
    *   @param String teachername
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TeacherService.findBy_Class
    *   @description CRUD ACTION findBy_Class
    *
    */
    findBy_Class(id: string): Observable<Teacher[]> {
        return this.http
            .get<Teacher[]>(this.contextUrl + '/findBy_Class/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * TeacherService.findBy_Exam
    *   @description CRUD ACTION findBy_Exam
    *
    */
    findBy_Exam(id: string): Observable<Teacher[]> {
        return this.http
            .get<Teacher[]>(this.contextUrl + '/findBy_Exam/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * TeacherService.findByclass
    *   @description CRUD ACTION findByclass
    *
    */
    findByClass(id: string): Observable<Teacher[]> {
        return this.http
            .get<Teacher[]>(this.contextUrl + '/findByclass/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * TeacherService.findByteachername
    *   @description CRUD ACTION findByteachername
    *
    */
    findByTeachername(id: string): Observable<Teacher[]> {
        return this.http
            .get<Teacher[]>(this.contextUrl + '/findByteachername/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * TeacherService.get
    *   @description CRUD ACTION get
    *   @param String id id
    *   @param String teachername
    *
    */
    get(id: string): Observable<Teacher> {
        return this.http
            .get<Teacher>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TeacherService.get_Class
    *   @description CRUD ACTION get_Class
    *   @param Number class
    *
    */
    get_Class(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Class')
            .pipe(
                map(response => response)
            );
     }

    /**
    * TeacherService.get_Exam
    *   @description CRUD ACTION get_Exam
    *   @param String examname
    *
    */
    get_Exam(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'get_Exam')
            .pipe(
                map(response => response)
            );
     }

    /**
    * TeacherService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Teacher[]> {
        return this.http
            .get<Teacher[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * TeacherService.update
    *   @description CRUD ACTION update
    *   @param String id id
    *   @param String teachername
    *
    */
    update(item: Teacher): Observable<Teacher> {
        return this.http
            .post<Teacher>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
