/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE ExamBase PLEASE EDIT ../exam.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

/**
 * This is the model of Exam object
 *
 */
export class ExamBase {

    constructor() { }

    public _id: string;
    public averageresult?: number;
    public class: number;
    public date: Date;
    public done?: Boolean;
    public examname: string;
    public maxmarks?: number;
    public roomno: string;
    public session: Date;
    public subjectname: string;
    public teachername: string;
    public timing?: string;
    // Relations m:m _Class
    public _Class: string[];
    // Relations m:m _Subject
    public _Subject: string[];
    // Relations m:m _Teacher
    public _Teacher: string[]}
