/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE LessonBase PLEASE EDIT ../lesson.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

/**
 * This is the model of Lesson object
 *
 */
export class LessonBase {

    constructor() { }

    public _id: string;
    public assignment?: Boolean;
    public class: number;
    public done?: Boolean;
    public lessonname?: string;
    public lessonno: number;
    public subjectname: string;
    public teachername: string;
    public test?: Boolean;
    // Relations m:m _Subject
    public _Subject: string[];
    // Relations m:m _Teacher
    public _Teacher: string[]}
